### ISSUE TITLE
Looking for sample FPC file for testing requirement

### ISSUE THREAD

**Issue by zahirbx** [ethanhart/pypacc#8]
Looking for sample FPC file for testing requirements
I cant seem to find such a file anywhere. Thanks in advance.

**Comment by ethanhart** [comment]
Hi @zahirbx, I have just added a "samples" directory which contains an FPC file. It is an old file I found in an email, so hopefully it works for you.

**Comment by zahirbx** [comment]
Very grateful Thank you!
